### ISSUE TITLE
Support file name and line number in ValidationError message

### ISSUE THREAD

**Issue by joschi36** [octodns/octodns#1027]
Type: Feature Request/Idea

I am currently building an OctoDNS GitHub Action with Python and wanted to use the [annotation feature](https://github.com/orgs/community/discussions/25002#discussioncomment-3246152) of GitHub. Unfortunately, the ValidationError error message only includes the zone and the error.

Current error message:
```
octodns.record.ValidationError: Invalid record test.com.
  - invalid IPv4 address "abc"
```

idea for future error message:
```
zones/test.com.yaml:L10:
octodns.record.ValidationError: Invalid record test.com.
  - invalid IPv4 address "abc"
```

Maybe this could also be implemented as a separate tool, like a linter perhaps? This would also open a whole range of new possibilities, like for instance give some custom linting rules (e.g. TTL not allowed lower/higer than X)

**Comment by ross** [comment]
Like the ideal. Figuring out how to go about it would probably require a fair bit of thinking/planning. The biggest issue would be getting the line number from the yaml parser. AFAIK it'd require something custom to get the line number of yaml elements as they are parsed. There are some results for that, e.g. https://stackoverflow.com/questions/13319067/parsing-yaml-return-with-line-number so it may be doable. 

After that it'd require figuring out a clean way to plumb the data through `Records.new` to get it to `Record.validate`, probably as an optional parameter. 

Ideally other types of sources would be supported as well, not just yaml, so there's probably some thinking/planning around the context being arbitrary so that other providers can pass in the context info that makes sense for them.

**Comment by ross** [comment]
Fixed by https://github.com/octodns/octodns/pull/1029
