### ISSUE TITLE
Feature Request: Bunny DNS Provider

### ISSUE THREAD

**Issue by Remarkable-Guille** [octodns/octodns#1051]
Create a provider for Bunny DNS API is a little similar to Cloudflare, so it probably won't be hard to do it

Bunny DNS API docs: https://docs.bunny.net/reference/dnszonepublic_index

Sadly, anything out of bash is out of my deep

**Comment by ross** [comment]
Hi @Remarkable-Guille BunnyDNS looks pretty interesting, along the lines of some of what can be done with PowerDNS in terms of scripting. 

Unfortunately it's tough for us to create providers for things we don't have access to. It does look like they have a free tier https://bunny.net/pricing/, but maybe only accessible during the 14 day trail? 

More broadly it's best for someone who's actively using the provider to be involved with it so they can make sure things keep working. Otherwise, there's always the option of (them/someone) funding the development & maintenance :grin:

**Comment by Remarkable-Guille** [comment]
I will contact them to see if there is interest in funding the development. Their service is very good, and Octodns should be a perfect fit. Let's see if I can broker a deal 🐙

**Comment by polarathene** [comment]
@Remarkable-Guille did you have any luck reaching out to Bunny?

**Comment by Remarkable-Guille** [comment]
Hi, I did contact them, but they said they have no interest in funding the developmentt :(
