### ISSUE TITLE
octodns-validate warnings logging as exit(1)

### ISSUE THREAD

**Issue by rschneider-chwy** [octodns/octodns#1091]
Hello! I'm having an issue with the newest warning added from #1060 where my Jenkins pipeline is failing due to the warning in place. 

```
[2023-10-20T16:01:03.137Z] + docker run --env-file environment.env ns1-dns octodns-validate --config-file=./octodns/config.yaml --all
[2023-10-20T16:01:04.060Z] 2023-10-20T16:01:03  [140534179903296] WARNING Record The SPF record type is DEPRECATED in favor of TXT values and will become an ValidationError in 2.0

script returned exit code 1
```

I would expect a warning to return `exit code 0` or for the `--all` flag to return `exit code 0` for any warnings, since no actual error has occurred. 

Without this functionality I will have the following three options:
1. Downgrade to before the warning was put in place
2. Add `--log-stream-stdout` and manually parse stdout for an error
3. Remove validation step all together

Thoughts? This happens even with `lienent: true` added to the config that has the SPF record

**Comment by ross** [comment]
The `-all` support was added to validate as of https://github.com/octodns/octodns/pull/1035.

Before that validate immediately exited on the first thing it found, in this case the SPF would do that.

The `-all` flag was added so that users could see all the problem. It does that by making the validation problems WARN rather than except https://github.com/octodns/octodns/blob/9102caa132a46c6714054c3d8cfaf0e2a5738500/octodns/record/base.py#L77-L82 and then if any warnings were printed it exits with a non-zero status code.

So this is behaving as expected. If `-all` is removed it'll throw an error on the SPF and exit immediatley (hiding any problems it sees after that.) 

If anything here the `WARNING` level would less than right/ideal. Could look at finding a way to change the warning to an error when run by validate, but not immediately clear how that'd work.

**Comment by istr** [comment]
I see three options here:

1. add something like an `--ignore-deprecation` flag to mute all warnings that are related to (upcoming) deprecation. This is what lots of other projects do.
2. revert the SPF warning message to an INFO message that won't fail the validation. Probably fastest to implement.
3. generally handle deprecation message to be INFO level and add a `--pedantic` flag to turn this into a warning/error (like some compilers do)

**Comment by ross** [comment]
I actually have a TODO to go through and convert all the deprecations to the formal python `DeprecationWarning`s

https://docs.python.org/3/library/exceptions.html#DeprecationWarning. 

That would address this specific SPF thing, if the problem here is that it's a deprecation. Any other validations would still behave the same though. 

I'd say option 4. is to convert the SPFs to TXT values as the actual SPF record type has long been deprecated and should be 100% functionally equivalent.

**Comment by rschneider-chwy** [comment]
I agree with option 4 as the final solution, which honestly I'll reach out and see if it can be updated. In general, I really appreciate that OctoDNS gives this sort of insight for flagging these non-standard configs. 

In regards to this feature request, as a user I'm more concerned with making OctoDNS fit our current NS1 config first then updating where we can. The lenience features are super helpful in that use case.

**Comment by istr** [comment]
I agree with option 4, see also

* https://github.com/octodns/octodns-constellix/pull/44#issuecomment-1763373653
* https://github.com/octodns/octodns-constellix/pull/44#issuecomment-1763456141

for a related discussion. The open question is still if we prefer to leave that to the users (conscious and manual config change) or provide some sort of automation for that before or after 2.0.

**Comment by ross** [comment]
> In regards to this feature request, as a user I'm more concerned with making OctoDNS fit our current NS1 config first then updating where we can. The lenience features are super helpful in that use case.

`octodns-validate` is intended to be used to show everything that isn't in-line with best practices/dns specs, to be used as part of a pre-commit and/or CI job blocking merges. 

It's definite an optional step and there's nothing wrong with just using octodns-sync and looking at the warnings/adding lenient's where needed (post 1.0) to get things happy. `strict_supports: false` is also an option, outside of octodns-validate, to go back to the pre-1.0 behavior of JUST warning and continuing when records don't validate, but I'd recommend `lenient` over that.

**Comment by rschneider-chwy** [comment]
Ah okay I see, so stick with the `octodns-sync` and `lenient` flags for this sort of use case. I can agree with that. I'd still want to print the warning to see what is recommended, but I can do that via a `try/catch`.

So just the change to `DeprecationWarnings` would be helpful to not fail the pipeline
