### ISSUE TITLE
YamlProvider plan not showing differences

### ISSUE THREAD

**Issue by tatnat** [octodns/octodns#1136]
Hello!

I'm not sure if this is by design but I noticed that when using YamlProvider as a target, any plans do not show any differences even if there is an existing `.yaml` file in the target directory with existing records. Essentially it seems like everything is being overwritten (which makes sense from a file perspective) but it'd be nice to see a diff in the plan with what's already existing.

Test zone file that's been placed in both source and target yaml directories:
```yaml
---
one:
  type: A
  value: 1.1.1.1
two:
  type: A
  value: 2.2.2.2
```

The plan that appears on every run:
```
********************************************************************************
* test.zone.io.
********************************************************************************
* targetyaml (YamlProvider)
*   Create Zone<test.zone.io.>
*   Create <ARecord A 3600, one.test.zone.io., ['1.1.1.1']> (sourceyaml)
*   Create <ARecord A 3600, two.test.zone.io., ['2.2.2.2']> (sourceyaml)
*   Summary: Creates=2, Updates=0, Deletes=0, Existing Records=0
********************************************************************************
```

**Comment by ross** [comment]
It is know/intentional. I thought it was documented, but looks like it's just a comment:

https://github.com/octodns/octodns/blob/e1d2c43174d7eb22f46f953723dfbb2c61a894ed/octodns/provider/yaml.py#L335-L338

I've looked adding support for using it as a target. It would be possible to get it to show diffs, but there's no real way to update an existing yaml file without blowing it away and writing everything from scratch, so you'd lose any comments and/or formatting. I could have sworn there was a branch pushed up with that in it, but I didn't find it now when looking. There's also a few issues where it's come up/been discussed in the past.

**Comment by tatnat** [comment]
Got it, thanks for the infor!
