### ISSUE TITLE
Feature request: Make it possible to choose record for auto ARPA

### ISSUE THREAD

**Issue by wjgauthier** [octodns/octodns#1158]
In a setup where multiple A/AAAA records point to the same IP, it would be great if you can choose which record should take preference when using the auto_arpa provider, for example by having an optional use_for_ptr option on those types of records.

Currently, I set `populate_should_replace` to true on the auto_arpa provider and `strict_supports` to false on the PowerDNS provider, which causes the first match to be used as the value of the PTR record. This is not always what I want.

If you think this feature makes sense, I can probably help out with a pull request.

**Comment by ross** [comment]
Something like this probably make sense. It may be preferable to have it be a priority rather than a flag to use this one, that way if the one with the flag set goes away the behavior would still make sense/be predictable. 

I think the main bits that would have to change are around here:

https://github.com/octodns/octodns/blob/e594f227c1d376d42d1b16d4f976dd7d575b0986/octodns/processor/arpa.py#L37-L40

It'd probably need something like:

```python
auto_arpa_priority = record.octodns.get('auto_arpa_priority', 0)
```

And then rather than have `self._records` be `set`s then could be a `list`s that a tuple is appended to:

```python
                    self._records[f'{ptr}.'].append((auto_arpa_priority, record.fqdn))
```

The `sorted` down here would do the right thing 

https://github.com/octodns/octodns/blob/e594f227c1d376d42d1b16d4f976dd7d575b0986/octodns/processor/arpa.py#L59

It'd just need to turn the list of tuples into a straight list of values

```python
fqdns = [d[1] for d in fqdns]
```

I guess the last question would be how it knows when to use just one (or more.) Maybe another parameter to `AutoArpa` tells it how many of `fqdn`s to use defaulting to a large number, `99999` or whatever.

Anyway, that's my 5m quick skim thoughts. I could be flipping how it all works in which case the detail of what I say above won't work, but I think the general ideas of priority and N should be doable regardless. 

Happy to 👁️ a PR. If not I'll get thrown onto the TODO stack and looked at sooner or later.

**Comment by ross** [comment]
Thanks
