### ISSUE TITLE
Document --force requirements

### ISSUE THREAD

**Issue by jaspermayone** [octodns/octodns#1170]
Hi,

I have browsed the docs for octodns and cannot seem to find what triggers a need for `--force` on a dns sync. We use octodns in production and need this info for creating workflows around running --force.

Thank you!

**Comment by ross** [comment]
There's a bit of info in the usage for the param: https://github.com/octodns/octodns/blob/ed13d2db52b4127f1035a8927a396467219b9918/octodns/cmds/sync.py#L24-L30

Otherwise errors are thrown when situations are encountered that require careful human review before aknowleding the changes and `--force`ing them.

https://github.com/octodns/octodns/blob/ed13d2db52b4127f1035a8927a396467219b9918/octodns/provider/plan.py#L14-L33
