### ISSUE TITLE
Print plan in machine consumable format

### ISSUE THREAD

**Issue by olivergondza** [octodns/octodns#1177]
First and foremost, thanks for providing this awesome tool!

While working on automating zone management in ansible, I would benefit from a way to load the plan (executed or from a dry-run), and work with the results.

This will enable customized reporting of what have changed, and customized logic to suspend `--doit` invocation. IOW, I would like the automation to never delete records, and never change more than 10 records without explicit ack from an administrator. Access to the summary and listing will enable users to implement all that.

To do that:

- It would be beneficial to send to stdout/file (not stderr), so it is easy to separate from logging messages of varying severity,
- and format it as json/yaml.

Thanks!

**Comment by ross** [comment]
There are currently a handful of `_PlanOutput`s available, located in https://github.com/octodns/octodns/blob/main/octodns/provider/plan.py. I could have sworn there was a JSON one, but apparently not. Doesn't look like any of them are particularly machine readable.  Would be fairly simple to create one.

Outputs are configured in the same way as processors, and there's a default `PlanLogger`:

https://github.com/octodns/octodns/blob/45753744a66982dd977de3bbe1ddceda07176e42/octodns/manager.py#L171-L180

PRs welcome, otherwise I'll stick it on the TODO list.

**Comment by ross** [comment]
Threw something together quickly while waiting on something else https://github.com/octodns/octodns/pull/1178

**Comment by mrwillrobbins** [comment]
Hi @ross, 

I was testing this and noticed the record.name was missing from the json output.  I needed this for pre/post checks so was perfect timing. 

I tested the below and seems to work.

```
class PlanJson(_PlanOutput):
    def __init__(self, name, indent=None, sort_keys=True):
        super().__init__(name)
        self.indent = indent
        self.sort_keys = sort_keys

    def run(self, plans, fh=stdout, *args, **kwargs):
        data = defaultdict(dict)
        for target, plan in plans:
            plan_data = {'changes': []}
            for change in plan.changes:
                record = change.record
                change_data = change.data
                change_data['name'] = record.name
                plan_data['changes'].append(change_data)
            data[target.id][plan.desired.name] = plan_data

        fh.write(dumps(data, indent=self.indent, sort_keys=self.sort_keys))
        fh.write('\n')
```
Thank you,
Will

**Comment by ross** [comment]
> was testing this and noticed the record.name was missing from the json output

Doh! That makes it pretty much unless. What I get for not having a use case for the results and not poking around at it. 

I'll probably look and see if there's a clean way to add the name to `Change.data` rather than manually put it into place in this one location. That should be a more robust fix if there's ever something like `PlanYaml` or whatever.
