### ISSUE TITLE
Feature Request: CoreDNS provider

### ISSUE THREAD

**Issue by fcolista** [octodns/octodns#1187]
Would it be possible to create a provider for CoreDNS?
Thank you!

**Comment by yzguy** [comment]
I've used CoreDNS a bit, from my experience it's definitely a "pull" model for getting records, eg getting them from a zone file, getting them from etcd/k8s/aws/mysql/git, etc.

OctoDNS being a push set up, there is no way that I'm aware of interacting with CoreDNS in a way that makes sense for a provider, nor is there a way to read records from it other than querying records normally

Realistically because CoreDNS can read from PowerDNS, ZoneFile, Hosts File, Route53, Azure DNS, GCP Cloud DNS. It would make more sense for a user to use one of those providers to manage it there and have CoreDNS pull records from that source.

**Comment by ross** [comment]
Thanks @yzguy. @fcolista that make sense?

It looks like maybe there's an AXFR plugin that will allow outgoing transfers, https://coredns.io/plugins/transfer/? Not 100% clear from the sparse info there w/o knowing more about CoreDNS itself. If that does allow AXFR you could use AXFR source to pull data out of CoreDNS as an octoDNS source. Doesn't seem like that's going to help get data into it.

**Comment by fcolista** [comment]
Thank you as first for your replies!
My scenario is quite simple:
I've an hidden master running CoreDNS, with bind-format zone file.
The other authoritative NS, running CoreDNS as well, AXFR from the hidden master.
I would like to manage the hidden master with OctoDNS.
AFAIU you suggestion is having the hidden master using the transfer plugin pulling data FROM the octodns instance.
Questions:
1. octodns works as DNS server?
2. My hidden master then will be run as secondary (slave) NS?

Thank you!

**Comment by yzguy** [comment]
@fcolista 

OctoDNS is not a DNS server, it's just a tool to manage DNS providers. The most common use is YAML as a source to manage the records, then having octoDNS sync those to various providers.

You could use the OctoDNS ZoneFileProvider to generate bind-format zone files, then have a process to transfer those to your CoreDNS server. Your CoreDNS server would then serve those records, and your secondary NS servers just perform normal AXFR zone transfers from your hidden master.

CoreDNS does not provide an API for record management so therefore there's not a provider to be written for it.

**Comment by fcolista** [comment]
Ok, got it.
CoreDNS does not have API and will never do (according with their developers: https://github.com/coredns/coredns/issues/522; https://github.com/coredns/coredns/issues/6254)
I ended up in using yaml to bind config, and copy the zonefile to CoreDNS.
Thanks.

**Comment by yzguy** [comment]
@fcolista Glad that helped!
