### ISSUE TITLE
The sorting algorithm can cause friction when adding new records

### ISSUE THREAD

**Issue by stantona** [octodns/octodns#1206]
We manage all of our DNS records using OctoDNS, including DNS verification records. These records tend to include a random sequence of alphanumeric characters. 

E.g:
```
_b9ab05b3cefa9cb63dcd2a98846zfd46.my.domain
```

We may have many of these in our various domain configuration files.

We understand that OcotoDNS uses a sort algorithm by padding integers with 0s to maintain natural order (as described in this [issue](https://github.com/octodns/octodns/issues/43)). 

Friction is encountered when we need to add a similar record, often times requiring trial and error before it is added to the right location because the sort order is not obvious just by eyeballing the value. 

We still want to enforce ordering, but since the sort order imposed by OctoDNS is not standard, it's difficult to use existing tools (short of building our own) to validate the order. 

Do you have suggestions on how we can improve our process here?

**Comment by ross** [comment]
> Do you have suggestions on how we can improve our process here?

As I assume you've already found, enforcing order is optional with the `enforce_order`

https://github.com/octodns/octodns/blob/6f8454ef7bb0a18b30a89b51de7e1933c2377576/octodns/provider/yaml.py#L36.

that's really the only option in the short term. 

Otherwise nothing prevents adding support for non-natural simplistic alphabetical sort order if that's what you're saying would work better, it's just really annoying in the most common case, e.g.

```yaml
---
foo-1:
   ...
foo-10:
   ...
foo-11:
   ...
foo-12:
   ...
foo-2:
   ...
foo-20:
   ...
foo-3:
   ...
...
```

I can poke around and see what that option would look like.
