### ISSUE TITLE
failed to find handler for key "directoryp

### ISSUE THREAD

**Issue by alphacabbage1** [octodns/octodns#1229]
Probably a minor thing, it certainly doesn't seem to affect functionality, but debug output may be of interest:

```
DEBUG Manager _config_providers: configuring providers
DEBUG Manager _build_kwargs: failed to find handler for key "directoryp 
DEBUG TinyDnsFileSource[config_example.com] __init__: id=config_example.com, directory=/srv/example.com/config/dns, default_ttl=3600
INFO  Manager __init__: provider=config_example.com (octodns.source.tinydns 1.10.0)
```

... for every zone-provider in the config file. In all cases, the `['providers']["config_{$domain}"]['directory']` is an absolute path.

It looks like manager.py's `split` sets handler empty;

`handler, name = v.split('/', 1)`

If any more info. would be useful, just let me know.

**Comment by ross** [comment]
It's a side effect of how the secret handlers work. They're configured with `<provider>/<value>` so that things like environmental variables would be: `env/SOME_API_KEY`. That also happens to match simple directories (on Linux) like `config/production` in which case it tries to find a secrets provider with the name `config` which wouldn't exist. 

In an ideal world a different form would have been used, but no matter what it was the same log would arise, just less often. 

There's more info in the code where that log message comes from:

https://github.com/octodns/octodns/blob/53a310ec518feef14f49f47ccc3d0d3bea16c975/octodns/manager.py#L425-L433

**Comment by ross** [comment]
The `p` is actually a type-o that shouldn't be there. Didn't even notice that.
