### ISSUE TITLE
DNSSEC specific record types

### ISSUE THREAD

**Issue by dschaper** [octodns/octodns#176]
Great project! 

The specific use case I'm looking at now is managing zones via DNSimple. All of our domains are DNSSEC, so we have DNSKEY records. (`AttributeError: 'DnsimpleProvider' object has no attribute '_data_for_DNSKEY'`) Normally this would be a straight multiple record type to implement. The concern that comes up on writing the PR for the record type is that this is not always something generated by the clients, and DNSimple rotates the records themselves on schedule. The APIv2 documentation shows that the record can be put by the client in addition to DNSimple's record generation. Tends to break any kind of idempotent scheme. That requires an update at the domain Registrar. I'm sure someone has come up against this previously, but I didn't see an issue referencing DNSSEC in my search.

**Comment by ross** [comment]
Hi @dschaper not sure how common DNSSEC use is for people looking at octoDNS, but it's not a case that has specifically been explored. Based on your description the best option may be for octoDNS to ignore DNSKEY records in cases where the provider is managing things. 

For `DnsimpleProvider` that'd probably be as easy as changing the `if _type == 'SOA':` line to `if _type not in self.SUPPORTS`, which is a bit more robust way to go about skipping unsupported records.

It's likely that a full pass of DNSSEC support would be nice to do at some point, but looking around DNS provider support for it is still pretty lacking so that point may not be yet, at least I probably won't have the time to dig into it soon 😁

**Comment by dschaper** [comment]
Thanks for the quick reply. I agree the best solution probably should be to skip it until the adoption is more prevalent. I'll try to get you a PR on that if I'm not beaten to it.

**Comment by yzguy** [comment]
From my semi-recent research and comparison of providers for DNSSEC, the support varies a lot.
Some will do Signing and Serve, some will only Serve, many don't support it. In the case of having two or more providers, it's almost operationally too complex to keep the zones in sync in a timely manner without AXFR.

I'm wondering if the functionality would more be in having a config option to label a zone as using DNSSEC, then if a re-signing needs to be manually done, OctoDNS could call the API endpoint, etc.

I think of this making sense in the case of PowerDNS, however most providers will do it behind the scenes on every record change or every time you publish the zone. I'd just imagine there would be a lot of issues having two providers signing independently, and keeping DS records updated to cover both.

**Comment by dschaper** [comment]
I'm going to lose this use case coming up. We've installed FreeIPA and are utilizing the built in BIND daemon with AXFR to secondary redundant providers. But the issues brought up are all very valid and until there's some sort of implmentation parity among the providers, this might end up a very messy solution, with DNSSEC that's something I don't think is the best option. Thank you for all the comments an insight.

**Comment by dschaper** [comment]
My research on this issue mirrors yzguy. It's just very early in implementation and no two providers will implement it in the same way. No problem with closing this out, I just think it will end up with various edge cases and confusion when one provider Sign/Serve and another Serve, while yet another requires rotation of valid signing keys to be updated at the registrar. We've actually pulled DNSSEC from all of our domains due to the non-standardized nature of implementation.

**Comment by ross** [comment]
No meaningful movement here, but I did run across https://blog.apnic.net/2021/08/25/multi-signer-dnssec-models/ which talks about multi-provider DNSSEC so that at least conceptually is a thing. I still don't have a personal use case for it so absent someone looking to contract its exploration & implementation it's probably not going to happen, but thought I'd link this up and reopen to house any thoughts/dicussion.

**Comment by ross** [comment]
Did a bit more digging a while back and I'm going to call this one not feasible. As far as I could find there are no commercial providers that let you provide the signing info and thus there's no real way to have multiple providers signing identically. It did not appear to be possible to provide both providers signing info so that either's signing would be allowed, though it's possible I missed something there.
