### ISSUE TITLE
SOA record

### ISSUE THREAD

**Issue by vanbroup** [octodns/octodns#39]
The SOA record is currently not supported by OctoDNS, the code states "would it even make sense?". I'm not aware if different providers support this record type in their API's but I think it would be best to keep records in sync where possible unless you have a good reason to keep them out of sync.

Comparing the SOA record for GitHub they don't match:
```
$ dig github.com @ns-1283.awsdns-32.org. SOA +short
ns-1707.awsdns-21.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

$ dig github.com @ns1.p16.dynect.net. SOA +short
ns1.p16.dynect.net. hostmaster.github.com. 1495621429 3600 600 604800 60
```

As reference the SOA record format:
```
primary ns; contact mail; serial number; refresh; retry; expiry; ttl
```

It probably doesn't matter who is listed as the primary nameserver for normal operation. While some DNS providers could rely on the primary nameserver for synchronization and want to have their own primary listed? As the name servers of different providers are intentionally not linked it should not cause any problems and it does indicate the clear separated operations.

The contact is set directly to GitHub at Dyn but for AWS it's not, the serial is different where this should normally be in sync for a normal setup. As the name servers are not linked and are not doing any zone transfers it should not cause any problems to have a different serial number (but could it hurt?).

The remaining SOA information (zone defaults) for refresh, retry, expiry and ttl is something I would like to keep in sync between my providers.

**Comment by ross** [comment]
> I'm not aware if different providers support this record type in their API's but I think it would be best to keep records in sync where possible unless you have a good reason to keep them out of sync.

Similar to [zone NS records](https://github.com/github/octodns/issues/38#issuecomment-303735453) early investigation showed management quirks around `SOA` record management across various providers and the decision was made to punt on managing them. 

> the serial is different where this should normally be in sync for a normal setup. As the name servers are not linked and are not doing any zone transfers it should not cause any problems to have a different serial number (but could it hurt?).

Yeah, serial is interesting. We do zone transfers in our internal setup, more coming soon in the previously mentioned blog post. For that is seems to be critical that each source/provider has a consistent serial, but not necessarily that they're consistent across them. 

> The remaining SOA information (zone defaults) for refresh, retry, expiry and ttl is something I would like to keep in sync between my providers.

Makes sense. By no means opposed to having support for `SOA` records so that these things can be managed and kept in sync, just something that was skipped due to being a bit more involved than normal records and not a super high priority for us. PRs welcome :grin:

**Comment by dorontal** [comment]
Same problem here.

An external check, using `mxtoolbox.com/domain/tracktunes.org` for my domain reports that there is a problem with DNS, the complaint is `Serial numbers do not match` and they say it's a problem with SOA records not matching.

When I check on the serial number, it comes up as "1".  Here's an nslookup transcript:
```
root@192.168.10.27: nslookup
> set type=soa
> tracktunes.org
Server:		192.168.10.1
Address:	192.168.10.1#53

Non-authoritative answer:
tracktunes.org	canonical name = tracktunes.github.io.

Authoritative answers can be found from:
github.io
	origin = ns-1622.awsdns-10.co.uk
	mail addr = awsdns-hostmaster.amazon.com
	serial = 1
	refresh = 7200
	retry = 900
	expire = 1209600
	minimum = 86400
```

**Comment by yzguy** [comment]
Having different serials won't cause an issue.

The serials are only used during zone transfers to know if the zone is up to date or needs to be updated. Using OctoDNS there will inherently be different serials between providers because each provider might use a different format, changes will be made at different times, etc.

However if you were using zone transfer between providers, then you wouldn't need to use OctoDNS to manage the secondary providers, you would just use it with the first one.
