### ISSUE TITLE
octodns-sync --continue

### ISSUE THREAD

**Issue by ramnes** [octodns/octodns#618]
I'm not sure how it works with multiple workers, but when you only have one, any error in applying any record will stop `octodns-sync`. Most of the time I would perfer the worker to continue its job, apply what it could, and report the different errors it encountered at the end. Is it a feature you would be interested in? Would a `--continue` flag make sense for this?

**Comment by ross** [comment]
Not opposed to the idea, but it may be pretty complicated to implement safely in practice, especially with the providers that support dynamic records that involve many api calls to modify. 

In general providers try and do their best to make changes in safe order, e.g. add a new "pool" of IPs to a dynamic record before modifying the "rules" so that we won't remove rules that point to valid existing pools if we failed to create a new "pool"

There are possibly similar, though less involved, cases like that with non-dynamic records.

**Comment by ramnes** [comment]
What I'm proposing is to jump to the next record, not to the next API call. If we can't create a new pool, we wouldn't try to modify the rules, just record the error and forget that record. Am I missing something obvious?

**Comment by ross** [comment]
Some providers have APIs that support batch/group changes of records so there's not a clear boundary between records when they're making changes. E.g. Route53 fails the whole batch if any one change isn't valid/going to be applied in which case the code would have to figure out which change set item(s) were causing problems and try the others.

**Comment by ramnes** [comment]
I see. That means we would have to implement, for each provider that uses batches, a mechanism to find out which record is faulty when an error happens, and then to rebuild the batch request without that record. Right?
