### ISSUE TITLE
How can we delete a zone?

### ISSUE THREAD

**Issue by ambersariya** [octodns/octodns#650]
How can we delete hosted zone for a domain that may no longer be of use. I have not found a way to delete hosted zone so far

**Comment by ross** [comment]
There isn't a way currently. So it'd require manual operation/deletes. 

Similar to configuration management stuff like `puppet` it would require some sort of `ensure => absent` marker to tell octoDNS to make it go away or alternatively a mechinism to tell octoDNS that it should manage zones in addition to records and remove any zones unknown to it (which seems dangerous and would never be a default on thing.)

Anyway, if it goes the `absent` direction it might look something like:

```
zones:
  going-away.com.:
    delete: true
```

If there's some sort of support managing all zones that'd probably be a manager level config thing, that if enabled would cause octoDNS to clear out zones it doesn't expect.

```
manager:
  manage_zones: true
```

Providers don't currently support deleting zones so the first step for this would be to define that api and then to implement it for all the providers in a reasonable way, i.e. things don't blow up if the provider doesn't. 

After that it'd be a matter of implementing one or both of the modes above.

I like the idea of managing zones, it just hasn't been a priority. I don't think there's an existing issue on the subject or at least I can't remember it coming up. I'm going to rename the issue to something more general in order to track the broader functionality. I'd like to see it, but I don't expect it to be implemented in the near future due to competing priorities.

**Comment by ambersariya** [comment]
Thank you for your detailed answer. I can totally understand why this wouldn't have been a priority. My use-case might be different as I get to manage many ephemeral domains. These domains span across many pages in Route53. I can remove records and sync that to a R53 but I can't then delete the hosted zone when no longer needed and that results in a charge. Currently this is a manual effort hence why my question. 😅 

I'd love to see where this issue goes.

**Comment by ross** [comment]
Going to leave this one as open. It's something that ideally we'd be able to support, but not super high priority thus hasn't been picked up as of yet.
