### ISSUE TITLE
Support for HTTP monitor

### ISSUE THREAD

**Issue by meghashyamps** [octodns/octodns#713]
We have some legacy endpoints in our production setup that still rely on monitors to check for HTTP body contains `<string>` for up/down. Which means the current implementation of TCP monitors (and TCP acting as HTTP) will not work for those use cases. I can confirm that DYN and NS1 already provide that option, and we have a work item to get this prioritized with Azure DNS as well.

What do you think about OctoDNS providing support for native HTTP monitors for DYN, NS1 and Azure? And perhaps calling out an explicit error message in route53 module saying that "HTTP response contains" check is not supported it at this time?

You briefly touched on HTTP monitors in [this](https://github.com/octodns/octodns/issues/710#issuecomment-841296696) comment, but hoping that now may be a good time revisit that topic as a separate requirement?

**Comment by ross** [comment]
Note that HTTP monitors are supported, it's just a detail of NS1 that they're using TCP to accomplish a HTTP check (more below.)

Main bit would be to find a way to get all the providers to behave the same in terms of looking for the output in the health check. That'd likely result in a new field in the health check config bits that adds the additional requirements to the provider setups.

### NS1

For NS1 I believe this could be accomplished by adding additional `Up Conditions`. Unfortunately I've lost access to the email communications with NS1 on the topic, but there were show-stopping issues with using their HTTP monitors for the semantics/behaviors that octoDNS expects and TCP monitors were the way to go.

Just for reference this is how it currently sets them up:

<img width="1327" alt="Screen Shot 2021-05-16 at 3 25 12 PM" src="https://user-images.githubusercontent.com/12789/118414678-e9c13f80-b65a-11eb-9f11-cddb49c00964.png">

### Route53

Looks like Route53 Healthchecks have a "Search string" field that will allow requiring a string to be in the output.

<img width="1022" alt="Screen Shot 2021-05-16 at 3 33 32 PM" src="https://user-images.githubusercontent.com/12789/118414893-145fc800-b65c-11eb-9554-07edfb3632e5.png">

### Dyn

That provider is EOL since they're shutting down the product (it's now way beyond their original date.) I don't really plan/expect to touch it before it's removed when it's fully shutdown.

### Azure

Azure doesn't currently support dynamic records. There's a PR, https://github.com/octodns/octodns/pull/706, with WIP support for `CNAME`s, but there are shortcomings preventing `A`/`AAAA` support so for now I don't think it's relevant.
