### ISSUE TITLE
Ignore some records

### ISSUE THREAD

**Issue by wolfedale** [octodns/octodns#752]
Hello!

There is a way to specify some sort of list of records that I would like to ignore? My problem is that some records I'm creating are from another place, another tool, calling GCP API. In this case every time when someone triggers octo-dns pipeline, it's trying to delete all of them. What's the best way to handle it?

**Comment by ross** [comment]
For the most part octoDNS is intended to be used when it owns all the records in the zone and that's the setup which is known to work extremely well and reliably. 

There is an **alpha** processor, [`OwnershipProcessor`](https://github.com/octodns/octodns/blob/master/octodns/processor/ownership.py) which was created to explore this use case. I've not used it for anything "production" and don't have anything where I will in the near future so it's likely to stay alpha for the foreseeable future (until a handful of people have used it in real situations and reported back that it works well.)

It works by creating companion TXT records for each octoDNS managed record. So if you specify

```yaml
hello:
    type: A
    value: 1.2.3.4
```

It will create that record and also a `TXT` record named `_octodns.hello.` which is used to tell octoDNS that it "owns" `hello.` and can modify it. 

The main hiccup with this pattern and something it would be impossible for octoDNS to handle would be error cases like the record being created w/o the ownership TXT or someone or something deleting the ownership TXT. All octoDNS can do is look for and trust the ownership TXT record. If something goes wrong with it human intervention will be required to get things back into a known good state.

See https://github.com/octodns/octodns/pull/751#issue-704832484 for an example of how to configure a processor.

**Comment by hsmade** [comment]
A use case for this, is when you have multiple data centers, and switch between them. This is typically done from monitoring systems. In this case, octoDNS should control the zone, but ignore changes on some records, as it would revert what the monitoring has switched.

**Comment by hsmade** [comment]
I'd be happy to do a PR for this, if you are open for it.

**Comment by ross** [comment]
As [stated above](https://github.com/octodns/octodns/issues/752#issuecomment-894237341) this is supported with the `OwnershipProcessor` so no PR is necessary.

**Comment by johnlane** [comment]
We have a use-case where a zone in Amazon Route53 has some "static" records that we want to manage with OctoDNS and some "dynamic" records that will be managed by Amazon EKS. I'd like to specify somehow that OctoDNS should ignore records matching, say, a regex that are found to exist on the DNS but are not represented in the OctoDNS zone config (i.e. a record present on route53 that OctoDNS doesn't know about and would otherwise want to delete).

The reason for match expressions rather than the approach of the OwnershipProcessor is that the records are dynamic and cannot be specified in advance but an expression that can be used to identify them can.

I wondered whether a processor could be used filter the delete list to prevent deleting of certain records. Would a processor be a way to achieve this?

**Comment by ross** [comment]
> The reason for match expressions rather than the approach of the OwnershipProcessor is that the records are dynamic and cannot be specified in advance but an expression that can be used to identify them can.

Ownership works by marking the records "owned" by octoDNS and then only managing those records. 

Alternatively you can implement a custom `Processor`, that would look much like the filter processors, and uses a regex or whatever logic you choose.

**Comment by ross** [comment]
Note that the Alpha processor API will be changing slightly with https://github.com/octodns/octodns/pull/761. The changes are fairly minor and it should make processors easier to work with and more performant (if/when it matters) as a result.

**Comment by sjparkinson** [comment]
Any chance you would consider a pull request to add a `RecordAllowlistFilter` class to the filter processor? I'm thinking config similar to:

```yaml
processors:
  only-specific-records:
    class: octodns.processor.filter.RecordAlowlistFilter
    allowlist:
      - www
```

Deleting records is then a two PR job, but that seems okay.

We have a similar EKS use case, and don't use OctoDNS to manage those zones as a result even if the majority of the records could be!

**Comment by ross** [comment]
Not opposed to the idea. The class should probably use "name" to more explicitly state what it's filtering on, e.g. `NameAllowListFilter` and we should probably add a coresponding `NameRejectListFilter` while we're in there. Probably makes sense to have the matchers be regexes since that'd cover an exact match case and allow more flexible filtering. Happy to 👀 a PR or stick it on my todo (when I get a chance) list, just lmk.

**Comment by ross** [comment]
Name filtering https://github.com/octodns/octodns/pull/932
