### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by parkr** [octodns/octodns#789]
hey @ross! I was just looking at whether this repo had a new version tagged and it's still v0.9.13. I was wondering if you're considering releasing a new version soon, since [there are about 250 commits since that tag was created](https://github.com/octodns/octodns/compare/v0.9.13...master). Not sure if this would be a v0.10.0 or a v1.0.0 or a v0.9.14, but figured I'd raise the flag and ask. Thanks!

**Comment by parkr** [comment]
🤘 Thanks so much, Ross! That is *quite* the diff. 😃

**Comment by rendragnet** [comment]
*grin* Aaaaand we're now tagging the version of octodns we use in our CI pipeline.. All the URLFWD's on our web properties disappeared overnight :D I was SO confused till I realised there'd been a new release overnight :).  VERY cool that you're supporting URLFWD on cloudflare now though, another thing we can have in source control, and not have to hit the web for!  Thankyou @ross  :)

**Comment by ross** [comment]
> _grin_ Aaaaand we're now tagging the version of octodns we use in our CI pipeline.

Yeah. I definitely recommend always pinning deps, especially things like octoDNS. 

Is CI auto-applying stuff? You're welcome to do that if you want, but I wasn't included to do so :grin:

**Comment by rendragnet** [comment]
> Is CI auto-applying stuff? You're welcome to do that if you want, but I wasn't included to do so 😁

Yeah, we have test+validate against cloudflare on all branches, and then test+validate+apply on the master branch - we do merge requests to master when we're wanting to apply changes.  There's a scheduled CI job every 4 hours to ensure what's on cloudflare matches source control.  We used to not have the scheduled job, and we would occasionally have the issue where someone went in via the web interface to add a new production server because they forgot about the 'new way' to do things - and 2 weeks later when someone did it the right way, the other server stops resolving ;). So the scheduled job was born, just so anything manually added fails fast.  It works very nicely and we don't get surprises.

**Comment by ross** [comment]
Ah the main bit makes sense and would make it a lot safer, now that it's pinned. If you pin it in a file in the repo you can probably also verify new releases on branches before merging them. That's the way it works at GitHub, though we don't auto apply.
