### ISSUE TITLE
HetznerDNS Provider / NS Records

### ISSUE THREAD

**Issue by talheim-it** [octodns/octodns#824]
Hello!

I am trying to add the NS Records in my octoDNS configuration too.

I have an interesting behavior at the moment:

```
'':
  - type: NS
    values:
      - hydrogen.ns.hetzner.com.
      - oxygen.ns.hetzner.com.
      - helium.ns.hetzner.de.
```
This option makes nothing, no changes.

If I use this option:
```
'@':
  - type: NS
    values:
      - hydrogen.ns.hetzner.com.
      - oxygen.ns.hetzner.com.
      - helium.ns.hetzner.de.
```
This options generates new entries with every run.

My question is if I configured it correctly or if I missed anything? Additionally if the coding is correct or if I made an issue.

Additionally A, MX and TXT records are in the '' field for the domain. 

Yours faithfully,
Mathias

**Comment by ross** [comment]
> I am trying to add the NS Records in my octoDNS configuration too.

I could have sworn it was in the README/docs somewhere, but apparently not, but octoDNS doesn't support managing apex `NS` records due to messes around how various providers deal with them. Some providers allow you to manage them completely, some allow you to add or remove extra values but won't let you touch their own NS values, and others won't let you do anything with them. 

I think it'd probably make sense to add a validation to the `NS` record type similar to the one on `CNAME`s that throws an error if you try to do it (unless `lenient` is included.)

The `@` is probably a ~bug in the Hetzner provider. I'm not familiar with it, but a quick glance at it seems like the provider under the hood expects `@` for apex records so the code is adding that as needed and removing it when things come back from the provider with `@`.  I don't know that the provider really needs to handle that case. I suppose octoDNS could throw an error when the name is `@` as that's otherwise not a legal name. I'll think about that.

See https://github.com/octodns/octodns/issues/38 for more info on the apex `NS` stuff and that issue tracks the maybe someday managing of them. This issue can stay open to record the one/two changes mentioned above.

**Comment by talheim-it** [comment]
@ross , yes you alright. It just confused me that there is an entry in the provider.py file naming the NS records which causes this to me.Additionally when you look at the "Provider" list, the "NS" record is marked in the supported records column. Maybe it would be more clear if those record is not named at this point to make it more clear.

**Comment by ross** [comment]
> Additionally when you look at the "Provider" list, the "NS" record is marked in the supported records column.

`NS` records are supported, just not at the "apex" (root) of the zone, since octoDNS itself doesn't support/allow that.

**Comment by ross** [comment]
> I suppose octoDNS could throw an error when the name is `@` as that's otherwise not a legal name. I'll think about that.

I'd forgotten some of the details of this and the hiccup that many of the APIs return the root NS records even though they don't fully allow managing them. Because of that it can't be considered an error/invalid record config and instead they're declared intelligible in https://github.com/octodns/octodns/blob/9da19749e28f68407a1c246dfdf65663cdc1c422/octodns/zone.py#L27-L30 meaning they're not considered when computing changers/diffs. Will think a bit more about it and explore options, but this may just end up staying the way it is.

**Comment by ross** [comment]
`@` symbol validation is added in https://github.com/octodns/octodns/pull/827.
