### ISSUE TITLE
azuredns provider fails to authenticate when reading values from environment variables

### ISSUE THREAD

**Issue by floatingsidewalk** [octodns/octodns#867]
There might be an issue with the Azure DNS provider.  I'm primarily developing on Windows 10; however using using Ubutu 18.04 LTS in a Windows Subsystem for Linux for executing Octodns.

When using environment variables for the AZURE_APPLICATION_ID, AZURE_DIRECTORY_ID, and AZURE_SUBSCRIPTION_ID, I end up with a failure to authenticate.

The console debug output shows URL's with returns embedded in the middle (%0D).  Examples: 

```
DEBUG urllib3.connectionpool https://management.azure.com:443 "GET /subscriptions/ea2f1fdb-2a23-4510-8976-2aff1bc306e1%0D/resourceGroups/
DEBUG urllib3.connectionpool https://login.microsoftonline.com:443 "POST /2932ee00-de9d-414f-9f20-e0f1235433df%0D/oauth2/token HTTP/1.1" 400 324
```

After adding a couple of statements to _build_kwargs method in manager.py (self.log.debug('Read argument: %s', repr(v))) 
It looks like there are '\r' characters on each variable.

```
2019-04-17T10:29:29  [139920198272832] DEBUG Manager Read argument: 'f8731d81-21fb-4a9f-a00e-ab24103518a1\r'
2019-04-17T10:29:29  [139920198272832] DEBUG Manager Read argument: 'ea2f1fdb-2a23-4510-8976-2aff1bc306e1\r'
```

If I add the ID's directly to the yaml, it seems to work.  I don't have a Linux only host to determine if this is specific to my environment.

Should Octodns strip out the CR ('\r') for variables when composing the request URLs?

**Comment by ross** [comment]
@floatingsidewalk Any idea where the `\r`s are coming from? It seems like maybe whatever source those are coming from may have windows line endings and whatever is being used to turn them into env vars isn't fully cleaning that up. 

We could add a trim/rtrim to the env variables, but that kind of worries me as it would lose the ability to put whitespace in the env variables in (unknown) cases where it may be required, e.g. gpg certs/keys and such.

I'd lean towards this being a problem with the setup outside of octoDNS rather than with the code itself, but would need more info to be sure.
