### ISSUE TITLE
Support DS record

### ISSUE THREAD

**Issue by baest** [octodns/octodns#967]
I know this is properly not the most commonly used record type, but we have DS records in our record set and it will be nice to have it be supported.
Example content of a DS record:
`2371 13 2 499E0967FB04F531204C56F6E8863FFF7CCEEED1469E8F26D85E2E42 54DD0CBB`

**Comment by yzguy** [comment]
Relevant Issue about DNSSEC support: #176

**Comment by baest** [comment]
Basically the DS record is put in parent zone and is used to validate the DNSKEYs in your zone. So DS will normally not be a record used, since it will be uploaded to the domain registrar. But in the case where you have signed a sub-zone then it becomes relevant. DNSKEYs are often auto generated I think (and that is what #176 says), so for me it is no problem at all to exclude them.
Again this is possible an edge use-case, but on the other hand it shouldn't require a lot of work so could be considered. I can possibly make a PR if there is a chance of it getting merged :)

**Comment by ross** [comment]
Not opposed to supporting the `DS` record type to support the use case of publishing the hash of the KSK. 

I've looked at overall DNSEC support a number of times, documented in https://github.com/octodns/octodns/issues/176, but there were also internal GitHub investigations/discussion. In the end DNSEC seems pretty flawed opertationally, at least in the way it's been implemented. I wish providers would let you manage your own keys and just provide them to them. Then we could actually get working DNSSEC across multiple providers. 

Anyway, happy to review a PR if one pops up. Otherwise I've left this tab open as a TODO list item when I get around to it.

**Comment by ross** [comment]
This is ready for people to submit PRs for providers to add support.
