### ISSUE TITLE
Support for planning all zones, but only applying some

### ISSUE THREAD

**Issue by ross** [octodns/octodns#982]
This would specifically be useful when doing arpa zones `auto-arpa` so that applying changes could be split up across runs, but we'd still have the "complete" picture to create PTR records from.

The main problem I can see with this sort of setup is that we'd be creating PTR records for the "desired" state of everything which may not match the "existing" state if there's anything unapplied. TBH I think this is a show-stopper for this functionality, but I wanted to get this issue written down to record any thinking/discussion.

No matter what this will require all the `populate` work to happen. That would include loading things from files and/or making api calls to other sources. 

In its simplest form it would also need to plan changes to all the zones, currently populate and plan are 1 step, which would make further API calls to populate the existing state. It could then only apply the specific zones indicated by the invocation.

It may be possible to skip the process of finding existing state and planning changes for zones that are not going to be applied. This would require some reworking/refactoring of `_populate_and_plan`.

/cc https://github.com/octodns/octodns/pull/974#discussion_r1083514238 @viranch which lead to this issue.

**Comment by viranch** [comment]
> The main problem I can see with this sort of setup is that we'd be creating PTR records for the "desired" state of everything which may not match the "existing" state if there's anything unapplied. TBH I think this is a show-stopper for this functionality

This is a good point. The best practice should be for desired state to not deviate from existing state for too long, making this a less of a problem in practice, but I agree in theory. We could populate the existing setup and base the arpa zone off it but that beats the practical purpose of targeted runs whose original intention would be to avoid making API calls for zones that haven't changed in the desired state.

> No matter what this will require all the populate work to happen. That would include loading things from files and/or making api calls to other sources.

This has similar potential problem: If the source is "expensive" to populate (ie calling API rather than reading from disk), that also beats the purpose of targeted runs similar to above.
